Repository Mokerstier/Rijksmuseum-Ticketflow, pull requests merged in 2020-05, with the labels that each got.

#18 Csv implement
  controllers/getter.js
  controllers/render.js
  data/articles.json
  data/expositions-periods.json
  data/expositions.json
  data/ticketshop-configuration.json
  package-lock.json
  package.json
  src/css/form.css
  src/css/form.less
  src/css/main.css
  src/css/main.less
  src/css/styles.css
  src/css/styles.less
  static/css/index.css
  views/pages/firstStep.ejs
  views/partials/head.ejs
Labels: enhancement

#28 :bug:fixed a bug with options -> values
  controllers/render.js
  views/pages/firstStep.ejs
Labels: bug

#41 Basis styling
  src/css/allButtons.css
  src/css/allButtons.less
  src/css/footer.css
  src/css/footer.less
  src/css/form.css
  src/css/form.less
  src/css/informationComponents.css
  src/css/informationComponents.less
  src/css/main.css
  src/css/main.less
  src/css/navigation.css
  src/css/navigation.less
  static/css/index.css
  views/pages/firstStep.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
Labels: enhancement

#49 flex gefixed in chrome
  src/css/form.css
  src/css/form.less
  static/css/index.css
  views/pages/secondStep.ejs
Labels: bug

#54 derde pagina styling
  src/css/allButtons.css
  src/css/allButtons.less
  src/css/footer.css
  src/css/footer.less
  src/css/form.css
  src/css/form.less
  src/css/informationComponents.css
  src/css/informationComponents.less
  src/css/main.css
  src/css/main.less
  static/css/index.css
  views/pages/firstStep.ejs
  views/pages/secondStep.ejs
  views/pages/thirdStep.ejs
Labels: enhancement

#55 rondleiding component hover/focus fix
  src/css/form.css
  src/css/form.less
  src/css/main.css
  src/css/main.less
  static/css/index.css
Labels: bug

#56 Form script
  src/js/first-form.js
  src/js/pricelist.js
  static/css/index.css
  static/js/index.js
  views/pages/firstStep.ejs
  views/partials/prijslijst.ejs
Labels: enhancement

#57 Form script
  src/js/first-form.js
  static/js/index.js
  views/pages/firstStep.ejs
Labels: enhancement

#58 route voor ons nieuwe idee
  controllers/render.js
  routes/index.js
  static/css/index.css
  views/pages/fifthStep.ejs
  views/pages/firstStep.ejs
  views/pages/fourthStep.ejs
  views/pages/secondStep.ejs
  views/pages/sixthStep.ejs
  views/pages/thirdStep.ejs
Labels: enhancement

#59 first stap new flow
  static/assets/images/Rijks foto's/gezin.jpg
  static/assets/images/Rijks foto's/groep.jpg
  static/assets/images/Rijks foto's/tour.jpg
  views/pages/firstStep.ejs
Labels: enhancement

#60 Solo ticket branch
  controllers/render.js
  data/ticketshop-configuration.json
  static/css/index.css
  views/pages/firstStep.ejs
  views/pages/secondStep.ejs
  views/partials/date.ejs
  views/partials/family.ejs
  views/partials/only.ejs
  views/partials/small-group.ejs
  views/partials/usps.ejs
Labels: enhancement

#62 date picker staat (ongeveer)
  src/css/form.css
  src/css/form.less
  static/css/index.css
  views/pages/fifthStep.ejs
  views/pages/fourthStep.ejs
  views/pages/thirdStep.ejs
Labels: enhancement

#74 group links fix
  static/css/index.css
  views/partials/date.ejs
  views/partials/family.ejs
  views/partials/only.ejs
  views/partials/small-group.ejs
Labels: bug

#86 dynamische dagen
  src/js/datePicker.js
  static/js/index.js
  views/pages/thirdStep.ejs
Labels: enhancement

#87 Date picker ERROR
  controllers/getter.js
  src/css/Entree-options.css
  src/css/Entree-options.less
  src/css/form.css
  src/css/form.less
  src/js/datePicker.js
  src/js/entreeOptionsText.js
  static/css/index.css
  static/js/index.js
  views/pages/thirdStep.ejs
Labels: bug

#89 button name and place fix
  static/css/index.css
  views/pages/fifthStep.ejs
  views/pages/fourthStep.ejs
  views/partials/date.ejs
  views/partials/family.ejs
  views/partials/only.ejs
  views/partials/small-group.ejs
Labels: enhancement

#92 fotos op de eerste pagina
  src/css/form.css
  src/css/form.less
  static/css/index.css
  views/pages/fifthStep.ejs
  views/pages/firstStep.ejs
Labels: enhancement

#93 Local storage branch
  controllers/render.js
  src/js/first-form.js
  src/js/local-storage.js
  static/css/index.css
  static/js/index.js
  views/pages/fifthStep.ejs
  views/pages/firstStep.ejs
  views/pages/fourthStep.ejs
  views/pages/secondStep.ejs
  views/pages/thirdStep.ejs
  views/partials/only.ejs
  views/partials/small-group.ejs
Labels: enhancement

#102 screenshots huidige situatie ticket-straat
  src/assets/wiki-images/original/extra_opties.png
  src/assets/wiki-images/original/extra_opties_ingevuld.png
  src/assets/wiki-images/original/overzicht_betalen.png
  src/assets/wiki-images/original/persoonsgegevens.png
  src/assets/wiki-images/original/ticket_opties.png
  static/css/index.css
Labels: documentation
