Repository Mokerstier/Rijksmuseum-Ticketflow, pull requests merged in 2020-06, with the labels that each got.

#105 Eerste pagina linkjes, tooltip bottom, derde pagina focus
  src/css/tooltip.css
  src/css/tooltip.less
  src/css/tour-ticket-cards.css
  src/css/tour-ticket-cards.less
  static/css/index.css
  views/pages/firstStep.ejs
Labels: enhancement

#107 refactored subtotals and ticketcount
  src/js/first-form.js
  src/js/local-storage.js
  static/css/index.css
  static/js/index.js
  views/pages/secondStep.ejs
  views/partials/date.ejs
  views/partials/family.ejs
  views/partials/only.ejs
  views/partials/small-group.ejs
Labels: bug

#109 :sparkles: fixed adding/ removing tickets with buttons +/ -
  src/js/first-form.js
  src/js/pricelist.js
  static/js/index.js
  views/partials/date.ejs
  views/partials/family.ejs
  views/partials/small-group.ejs
Labels: enhancement

#110 fixed bugs in datePicker + added deeper sorting dayperiods
  src/js/datePicker.js
  static/js/index.js
  views/pages/thirdStep.ejs
Labels: bug

#108 Update README.md concept en probleem
  README.md
Labels: documentation

#115 Navigatie style wanneer page bezocht is (goede pull request)
  src/css/navigation.css
  src/css/navigation.less
  static/css/index.css
  views/pages/fifthStep.ejs
  views/pages/fourthStep.ejs
  views/pages/secondStep.ejs
  views/pages/sixthStep.ejs
  views/pages/thirdStep.ejs
Labels: enhancement

#121 h2 en legend overal toegevoegd en styling
  src/css/form.css
  src/css/form.less
  src/css/main.css
  src/css/main.less
  src/css/tour-ticket-cards.css
  src/css/tour-ticket-cards.less
  src/js/datePicker.js
  static/css/index.css
  static/js/index.js
  views/pages/fifthStep.ejs
  views/pages/firstStep.ejs
  views/pages/fourthStep.ejs
  views/pages/secondStep.ejs
  views/pages/thirdStep.ejs
  views/partials/date.ejs
  views/partials/family.ejs
  views/partials/only.ejs
  views/partials/small-group.ejs
  views/partials/usps.ejs
Labels: enhancement

#125 hover/focus animaties
  src/assets/images/ticket.png
  src/css/allButtons.css
  src/css/allButtons.less
  src/css/focus-hover-styling.css
  src/css/focus-hover-styling.less
  src/css/footer.css
  src/css/footer.less
  src/css/form.css
  src/css/form.less
  src/css/main.css
  src/css/main.less
  src/css/navigation.css
  src/css/navigation.less
  src/css/tickets-choice.css
  src/css/tickets-choice.less
  src/css/tooltip.css
  src/css/tooltip.less
  src/css/tour-ticket-cards.css
  src/css/tour-ticket-cards.less
  static/assets/images/ticket.png
  static/css/index.css
  views/pages/fifthStep.ejs
  views/pages/firstStep.ejs
  views/pages/fourthStep.ejs
  views/pages/secondStep.ejs
  views/pages/sixthStep.ejs
  views/pages/thirdStep.ejs
  views/partials/date.ejs
  views/partials/family.ejs
  views/partials/footer.ejs
  views/partials/only.ejs
  views/partials/small-group.ejs
Labels: enhancement

#126 Form server side fix
  controllers/getter.js
  controllers/render.js
  data/articles.json
  routes/index.js
  src/js/datePicker.js
  static/css/index.css
  static/js/index.js
  views/pages/dayStep.ejs
  views/pages/fifthStep.ejs
  views/pages/fourthStep.ejs
  views/pages/monthStep.ejs
  views/pages/secondStep.ejs
  views/pages/sixthStep.ejs
  views/pages/thirdStep.ejs
  views/pages/timeStep.ejs
  views/partials/date.ejs
  views/partials/datepicker.ejs
  views/partials/family.ejs
  views/partials/only.ejs
  views/partials/small-group.ejs
Labels: enhancement

#135 Error handling ticket group
  controllers/getter.js
  controllers/render.js
  src/css/Entree-options.css
  src/css/Entree-options.less
  src/css/focus-hover-styling.css
  src/css/focus-hover-styling.less
  src/css/form.css
  src/css/form.less
  src/js/datePicker.js
  src/js/first-form.js
  static/css/index.css
  static/js/index.js
  views/pages/test.ejs
  views/pages/thirdStep.ejs
Labels: enhancement

#136 :bug: bugfix in input check resolved & checkForm on load
  src/js/datePicker.js
  static/js/index.js
  views/pages/thirdStep.ejs
Labels: bug

#132 foto's kleiner en reduce motion
  src/assets/images/RijksFotos/date.jpg
  src/assets/images/RijksFotos/gezin.jpg
  src/assets/images/RijksFotos/groep.jpg
  src/assets/images/RijksFotos/groepKinderen.jpg
  src/assets/images/RijksFotos/groteFotos/date.jpeg
  src/assets/images/RijksFotos/groteFotos/gezin.jpg
  src/assets/images/RijksFotos/groteFotos/groep.jpg
  src/assets/images/RijksFotos/groteFotos/groepKinderen.jpg
  src/assets/images/RijksFotos/groteFotos/tourtype1.jpg
  src/assets/images/RijksFotos/groteFotos/tourtype2.jpg
  src/assets/images/RijksFotos/groteFotos/tourtype3special.jpg
  src/assets/images/RijksFotos/groteFotos/tourtype4.jpg
  src/assets/images/RijksFotos/tourtype1.jpg
  src/assets/images/RijksFotos/tourtype2.jpg
  src/assets/images/RijksFotos/tourtype3special.jpg
  src/assets/images/RijksFotos/tourtype4.jpg
  src/css/focus-hover-styling.css
  src/css/focus-hover-styling.less
  src/css/form.css
  src/css/form.less
  src/js/datePicker.js
  static/assets/date.jpg
  static/assets/images/RijksFotos/1date.jpeg
  static/assets/images/RijksFotos/RijksFotos.jpg
  static/assets/images/RijksFotos/date.jpg
  static/assets/images/RijksFotos/gezin.jpg
  static/assets/images/RijksFotos/groep.jpg
  static/assets/images/RijksFotos/groepKinderen.jpg
  static/assets/images/RijksFotos/groteFotos/date.jpeg
  static/assets/images/RijksFotos/groteFotos/gezin.jpg
  static/assets/images/RijksFotos/groteFotos/groep.jpg
  static/assets/images/RijksFotos/groteFotos/groepKinderen.jpg
  static/assets/images/RijksFotos/groteFotos/tourtype1.jpg
  static/assets/images/RijksFotos/groteFotos/tourtype2.jpg
  static/assets/images/RijksFotos/groteFotos/tourtype3special.jpg
  static/assets/images/RijksFotos/groteFotos/tourtype4.jpg
  static/assets/images/RijksFotos/tourtype1.jpg
  static/assets/images/RijksFotos/tourtype2.jpg
  static/assets/images/RijksFotos/tourtype3special.jpg
  static/assets/images/RijksFotos/tourtype4.jpg
  static/css/index.css
  static/js/index.js
  views/pages/firstStep.ejs
  views/pages/thirdStep.ejs
  views/partials/datepicker.ejs
Labels: enhancement

#141 aria toegevoegd
  src/css/form.css
  src/css/form.less
  src/js/first-form.js
  static/css/index.css
  static/js/index.js
  views/pages/fifthStep.ejs
  views/pages/fourthStep.ejs
  views/pages/thirdStep.ejs
  views/partials/date.ejs
  views/partials/family.ejs
  views/partials/head.ejs
  views/partials/only.ejs
  views/partials/small-group.ejs
Labels: enhancement

#142 focus blijft centraal
  src/js/focus-center.js
  static/js/index.js
Labels: enhancement

#143 Submit button disabled
  controllers/getter.js
  controllers/render.js
  src/css/allButtons.css
  src/css/allButtons.less
  src/js/asubmit-button.js
  src/js/datePicker.js
  src/js/first-form.js
  src/js/ticketsBackgroundImages.js
  static/css/index.css
  static/js/index.js
  views/pages/dayStep.ejs
  views/pages/fifthStep.ejs
  views/pages/fourthStep.ejs
  views/pages/monthStep.ejs
  views/pages/secondStep.ejs
  views/pages/sixthStep.ejs
  views/pages/test.ejs
  views/pages/thirdStep.ejs
  views/pages/timeStep.ejs
  views/partials/header.ejs
  views/partials/only.ejs
Labels: bug, enhancement

#145 fixed time parser and added time element
  src/js/datePicker.js
  static/js/index.js
Labels: bug, enhancement

#175 eerste issues van roger
  src/css/form.css
  src/css/form.less
  src/js/datePicker.js
  static/css/index.css
  static/js/index.js
  views/pages/fourthStep.ejs
  views/pages/secondStep.ejs
  views/pages/sixthStep.ejs
  views/partials/datepicker.ejs
Labels: ARIA, enhancement

#176 deel twee feedback roger
  src/css/tickets-choice.css
  src/css/tickets-choice.less
  src/js/first-form.js
  src/js/selectWithEnter.js
  static/css/index.css
  static/js/index.js
  views/pages/thirdStep.ejs
Labels: ARIA, bug, enhancement

#177 Notes test 2
  controllers/render.js
  documentation/test1/11-06-20-TEST#2-RR.md
  src/js/datePicker.js
  static/css/index.css
  static/js/index.js
Labels: documentation

#178 Reduce motion + form vijfde stap
  src/css/fifth-step-form.css
  src/css/fifth-step-form.less
  src/css/focus-hover-styling.css
  src/css/focus-hover-styling.less
  static/css/index.css
Labels: enhancement

#181 styling js flow geen js
  views/pages/dayStep.ejs
  views/pages/monthStep.ejs
  views/pages/timeStep.ejs
Labels: enhancement

#183 Styling op only page
  controllers/getter.js
  controllers/render.js
  src/assets/images/green-ticket.png
  src/css/focus-hover-styling.css
  src/css/focus-hover-styling.less
  src/css/tickets-choice.css
  src/css/tickets-choice.less
  src/js/asubmit-button.js
  src/js/datePicker.js
  src/js/first-form.js
  src/js/multimedia.js
  src/js/selectWithEnter.js
  static/assets/images/green-ticket.png
  static/css/index.css
  static/js/index.js
  views/pages/thirdStep.ejs
  views/partials/only.ejs
Labels: enhancement

#180 console log eruit
  controllers/getter.js
  controllers/render.js
  src/js/asubmit-button.js
  src/js/datePicker.js
  src/js/first-form.js
  src/js/multimedia.js
  src/js/selectWithEnter.js
  static/js/index.js
  views/pages/thirdStep.ejs
Labels: enhancement

#184 Update README.md
  README.md
Labels: documentation

#186 Bestellinglijst branch
  controllers/render.js
  data/ticketshop-configuration.json
  src/css/tour-ticket-cards.css
  src/css/tour-ticket-cards.less
  src/js/datePicker.js
  src/js/entreeOptionsText.js
  src/js/local-storage.js
  src/js/multimedia.js
  static/css/index.css
  static/js/index.js
  views/pages/fifthStep.ejs
  views/pages/fourthStep.ejs
  views/pages/thirdStep.ejs
  views/partials/prijslijst.ejs
Labels: enhancement

#188 media queries en form styling
  src/css/fifth-step-form.css
  src/css/fifth-step-form.less
  src/css/form.css
  src/css/form.less
  src/css/querymedia.css
  src/css/querymedia.less
  static/css/index.css
  views/pages/fifthStep.ejs
Labels: bug, enhancement

#189 Update README.md
  README.md
Labels: documentation

#191 Update README.md
  README.md
Labels: documentation

#193 local storage done for every step
  src/js/local-storage.js
  static/css/index.css
  static/js/index.js
Labels: enhancement

#194 Update README.md
  README.md
Labels: documentation

#206 Notes test 3
  documentation/test1/16-06-2020-TEST#3-J.MD
Labels: documentation

#202 Update README.md
  README.md
Labels: documentation

#208 Scrollintoview branch
  controllers/render.js
  src/js/datePicker.js
  src/js/local-storage.js
  src/js/main.js
  static/js/index.js
Labels: enhancement

#209 Footer met inhoud en styling
  src/css/footer.css
  src/css/footer.less
  src/css/querymedia.css
  src/css/querymedia.less
  static/css/index.css
  views/partials/footer.ejs
Labels: enhancement

#210 Datepicker date branch
  controllers/render.js
  src/css/form.css
  src/css/form.less
  src/js/datePicker.js
  src/js/local-storage.js
  src/js/multimedia.js
  static/css/index.css
  static/js/index.js
Labels: bug, console

#211 Update README.md
  README.md
Labels: documentation

#214 Update README.md
  README.md
Labels: documentation
